server:
  port: 8002 # 本服务端口号
  servlet:
    context-path: /homepage-user # 传入进来的请求 URL 前缀

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/ # 服务注册中心地址

spring:
  application:
    name: eureka-client-homepage-user # 用户微服务在注册中心中的名称
  datasource:
    url: jdbc:mysql://localhost:3306/homepage_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver